name: zigzag
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6
  logging: ^1.1.1
  gap: ^3.0.0
  go_router: ^9.1.1
  intl: any
  get_it: ^7.6.0
  wolt_modal_sheet: ^0.1.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  riverpod_generator: ^2.2.1
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
  #      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true